name: CI

on: push

permissions:
  checks: write

jobs:
  clippy_check:
    name: Check code with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --color always
          name: Clippy report
